EditableFlask/views.py
import os
import json
from jinja2.environment import copy_cache
from flask import Blueprint, current_app, render_template, request, redirect, url_for
from datetime import datetime
from zipfile import ZipFile
import urllib.parse
import shutil

def CreateLoginManager(current_app, User):
    from flask_login import LoginManager, UserMixin, login_required, logout_user, current_user, login_user
    from werkzeug.security import generate_password_hash, check_password_hash
    from werkzeug.utils import secure_filename
    login_manager = LoginManager()
    login_manager.login_view = '/edits'+current_app.config['LOGIN_ROUTE']
    login_manager.init_app(current_app)
    @login_manager.user_loader
    def load_user(user_id):
        """Flask-Login callback to load a user from the database by ID."""
        return User.query.get(int(user_id))
def OrginalLocation(location):
    directory = os.path.dirname(location)
    return os.path.join(directory, '')

edits = Blueprint('edits', __name__, template_folder='templates', static_folder='assets')

@edits.route('/static')
@edits.route('/static/<path:page>')
def retrive_static(page=None):
    if page:
        page = urllib.parse.unquote(page)
    STATIC_PATH = os.path.join(current_app.config['FILE_PATH'],current_app.static_folder)
    if not os.path.exists(STATIC_PATH):
        os.mkdir(STATIC_PATH)
    if page:
        folder_location = 'static/'+page
        FolderPath = STATIC_PATH + '/'+page
    else:
        folder_location = 'static'
        FolderPath = STATIC_PATH
    contents = {}
    for root, folders, files in os.walk(FolderPath):
        if root == FolderPath: 
            for folder in folders:
                relative_location = os.path.relpath(os.path.join(root, folder), STATIC_PATH)
                folder_path = os.path.join(root, folder)
                folder_stats = os.stat(folder_path)
                contents[folder] = {
                    "type": "folder",
                    "name": folder,
                    "location": '/static/'+relative_location,
                    "last_modified": datetime.fromtimestamp(folder_stats.st_mtime).strftime("%Y-%m-%d %H:%M:%S"),
                    "size": str(round(folder_stats.st_size / 1024, 2))+" KiB",
                }
            for file in files:
                file_path = os.path.join(root, file)
                relative_location = os.path.relpath(file_path, STATIC_PATH)
                file_stats = os.stat(file_path)  # Get file stats
                filename, extension = os.path.splitext(file)
                contents[file] = {
                    "type": "file",
                    "name": filename+extension,
                    "extension": extension,
                    "location": '/static/'+relative_location,
                    "last_modified": datetime.fromtimestamp(file_stats.st_mtime).strftime("%Y-%m-%d %H:%M:%S"),
                    "size": str(round(file_stats.st_size / 1024, 2))+" KiB",
                }
    return render_template('static.html', contents=contents, folder_location=folder_location) 

@edits.route('/static-view/<path:page>', methods=['POST'])
def static_view(page=None):
    location = request.form.get('location')
    if page == 'upload':
        files = request.files['file']
        files.save(os.path.join(current_app.config['FILE_PATH'],location, request.form.get('file_name')))
    elif page == 'create_folder':
        new_folder_path = os.path.join(current_app.config['FILE_PATH'], location, request.form.get('folder_name'))
        if not os.path.exists(new_folder_path):
            os.makedirs(new_folder_path)
    elif page == 'unzip':
        location = request.form.get('detail_location')
        location = current_app.config['FILE_PATH']+location
        new_folder_path, _ = os.path.splitext(location)
        if not os.path.exists(new_folder_path):
            os.makedirs(new_folder_path)
        with ZipFile(location, 'r') as zObject: 
            zObject.extractall(path=new_folder_path) 
    elif page == 'delete':
        location = request.form.get('detail_location')
        location = current_app.config['FILE_PATH']+location
        if os.path.exists(location):
            if os.path.isfile(location):
                os.remove(location)
            elif os.path.isdir(location):
                shutil.rmtree(location)  
    elif page == 'back':
        parts = location.split('/')
        parent_directory = '/'.join(parts[1:-1])  # Join parts starting from index 1 to the second-to-last index
        if parent_directory == '':
            return redirect(url_for('edits.retrive_static', page=None))
        return redirect(url_for('edits.retrive_static', page=parent_directory))
    elif page == 'rename':
        location = location+'/'+request.form.get('name')
        if os.path.exists(location):
            if os.path.isfile(location):
                directory = os.path.dirname(location)
                new_name = request.form.get('file_folder_name')
                base_name = new_name
                extension = os.path.splitext(location)[1]
                if new_name.find('.') != -1:
                    base_name, extension = os.path.splitext(new_name)
                new_location = os.path.join(directory, base_name + extension)
                os.rename(location, new_location)
            elif os.path.isdir(location):  # If it's a directory
                new_name = request.form.get('file_folder_name')
                new_location = os.path.join(os.path.dirname(location), new_name)
                os.rename(location, new_location)
    elif page == 'search':
        folder_path = current_app.config['FILE_PATH']+'/'+location
        search_input = request.form.get('searchInput')
        search_input = search_input.lower()
        contents = {}
        for root, folders, files in os.walk(folder_path):
            for folder in folders:
                if search_input in folder.lower():  # Compare in lowercase
                    relative_location = os.path.relpath(os.path.join(root, folder), folder_path)
                    folder_stats = os.stat(os.path.join(root, folder))
                    contents[folder] = {
                        "type": "folder",
                        "name": folder,
                        "location": '/static/'+relative_location,
                        "last_modified": datetime.fromtimestamp(folder_stats.st_mtime).strftime("%Y-%m-%d %H:%M:%S"),
                        "size": str(round(folder_stats.st_size / 1024, 2))+" KiB",
                    }
            for file in files:
                if search_input in file.lower():  # Compare in lowercase
                    file_path = os.path.join(root, file)
                    relative_location = os.path.relpath(file_path, folder_path)
                    file_stats = os.stat(file_path)  # Get file stats
                    filename, extension = os.path.splitext(file)
                    contents[file] = {
                        "type": "file",
                        "name": filename+extension,
                        "extension": extension,
                        "location": '/static/'+relative_location,
                        "last_modified": datetime.fromtimestamp(file_stats.st_mtime).strftime("%Y-%m-%d %H:%M:%S"),
                        "size": str(round(file_stats.st_size / 1024, 2))+" KiB",
                    }
        return render_template('static.html', contents=contents, searched_location=folder_path) 
    location = request.form.get('location')
    parts = location.split('/')
    if len(parts) == 1:
        location=None
    else:
        location = '/'.join(parts[-1:])
    return redirect(url_for('edits.retrive_static', page=location))

@edits.route('/')
@edits.route('/<path:page>')
def index(page=None):
    _db = current_app.jinja_env.edits
    if _db:
        if not page or page not in _db:
            page = next(iter(_db.keys())) if _db else None
    else:
        page = None
    return render_template('edits-admin.html',
                            edits=_db,
                            page=page,
                            summernote=current_app.config['EDITS_SUMMERNOTE'],
                            preview=current_app.jinja_env.edits_preview)
                            
@edits.route('/preview', methods=['POST'])
def preview():
    if request.form.get('state') == 'true':
        preview = True
        cache = None
    else:
        preview = False
        cache = copy_cache(current_app.jinja_env.edits_cache)

    current_app.jinja_env.edits_preview = preview
    current_app.jinja_env.cache = cache

    if current_app.jinja_env.cache:
        current_app.jinja_env.cache.clear()

    return ''

@edits.route('/save', methods=['POST'])
def save():
    _db = current_app.jinja_env.edits
    page = request.form.get('page')
    for field in request.form:
        if field != 'page' and field != 'files':  # Skip 'files' field
            value = request.form.get(field)
            if value == '':
                value = None
            _db[page][field]['edited'] = value
    if current_app.jinja_env.cache:
        current_app.jinja_env.cache.clear()
    with open(current_app.config['FILE_PATH']+'edits.json', 'w') as f:
        f.write(json.dumps(_db, indent=4))
    return redirect(url_for('edits.index', page=page))



    

EditableFlask/templates/edits-admin.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Editable Flask</title>
    <link rel="icon" type="image/x-icon" href="/static/favicon.ico">
    <link href="{{ url_for('edits.static', filename='bootstrap/css/bootstrap.min.css')}}" rel="stylesheet" />
    <link href="{{ url_for('edits.static', filename='bootstrap/css/navbar.css')}}" rel="stylesheet" />
    <link href="{{ url_for('edits.static', filename='bootstrap-switch/css/bootstrap-switch.min.css') }}" rel="stylesheet">

    {% if summernote %}
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/codemirror.min.css" rel="stylesheet" />
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet" />
    {% endif %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style>
      .btn-logout {
        background-color: red;
        color: white;
        padding: 5px 10px;
        border: none;
        border-radius: 4px;
        font-size: 14px;
        margin-left: 15px;
      }
    
      .btn-logout:hover {
        background-color: rgb(226, 26, 26); 
        color: #eee;/* Darker red on hover */
      }
    </style>
    
  </head>

  <body>
    <div class="container">
      <div class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="#">EditableFlask</a>
          </div>
          <div class="pull-right" style="margin-top: 6px;">
              <label style="font-weight: normal; vertical-align:middle;">Preview</label>
              &nbsp;&nbsp;
              <input type="checkbox" name="mode" {% if preview %}checked{% endif %} />
              <a type="submit" href="/edits/logout" class="btn btn-logout">Logout</a>
            </div>
        </div>
      </div>

      {% if edits|length %}
      <div class="row">
        <div class="col-sm-4">
          <div class="panel panel-default">
            <div class="panel-heading">Editable Pages</div>
            <div class="list-group">
              {% for page, regions in edits.items() %}
                <a href="{{ url_for('edits.index', page=page) }}" class="list-group-item">
                  <span class="badge">{{ regions.keys()|length }}</span>
                  {{ page }}
                </a>
              {% endfor %}
              <a href="{{ url_for('edits.index', page='static') }}" class="list-group-item">
                <span class="badge"></span>
                STATIC
              </a>
            </div>
          </div>
        </div>
        <div class="col-sm-8">
            <p class="lead">Editing {{ page }}</p>
            <form method="POST" action="{{ url_for('edits.save') }}" onsubmit="save()">
              <input type="hidden" name="page" value="{{ page }}" />
              {% for key, section in edits[page].items() %}
              <small><strong>{{ key|upper }}</strong></small>
              <div class="form-group" style="margin-top: 5px;">
                  {% if summernote %}
                  <div class="summernote" id="{{ key }}">{{ section.edited if section.edited is not none else section.original }}</div>
                  <!-- Add a hidden input field to submit the Summernote content -->
                  <input type="hidden" name="{{ key }}" value="{{ section.edited if section.edited is not none else section.original }}" />
                  {% else %}
                  <textarea class="form-control" rows="4" name="{{ key }}">{{ section.edited if section.edited is not none else section.original }}</textarea>
                  {% endif %} 
              </div>
              {% endfor %}
              <input type="submit" value="Save Page" class="btn btn-primary" />
          </form>
          
        </div>
      </div>
      {% else %}
      <div class="row">
        <div class="col-sm-12" style="text-align: center; padding-top: 40px;">
          <i class="glyphicon glyphicon-warning-sign" style="font-size: 100px; color: #eee;"></i>
          <p class="lead" style="width: 50%; margin: 0 auto; padding-top: 40px;">No editable pages loaded yet. After adding editable regions to your templates, visit each page in your browser to load it.</p>
        </div>
      </div>
      {% endif %}
    </div>
  </body>

  <script type="text/javascript" src="//code.jquery.com/jquery-1.9.1.min.js"></script> 
  <script type="text/javascript" src="{{ url_for('edits.static', filename='bootstrap-switch/js/bootstrap-switch.min.js') }}"></script>

  {% if summernote %}
  <script type="text/javascript" src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script> 
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/codemirror.min.js"></script>
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/mode/xml/xml.min.js"></script>
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/codemirror/2.36.0/formatting.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
  {% endif %}

  <script>
    $(document).ready(function() {
      $('[name="mode"]').bootstrapSwitch({
        onText: 'On',
        offText: 'Off',
        onSwitchChange: function(e, state) {
          $.post("{{ url_for('edits.preview') }}", {state: state});
        }
      });

      {% if summernote %}
      $(document).ready(function() {
  $('.summernote').each(function() {
    $(this).summernote({
      height: 100,
      toolbar: [
        ['style', ['bold', 'italic', 'underline', 'clear']],
        ['insert', ['link', 'picture', 'video', 'hr', 'table']],
        ['font', ['fontname', 'fontsize', 'fontsizeunit', 'color', 'forecolor', 'backcolor']],
        ['paragraph', ['style', 'ol', 'ul', 'paragraph', 'height']],
        ['misc', ['fullscreen', 'codeview', 'undo', 'redo', 'help']]
      ]
    });
  });
});

      {% endif %}
    });

    {% if summernote %}
    function save() {
    $('.summernote').each(function() {
        var content = $(this).summernote('code');
        $(this).siblings('input[type="hidden"]').val(content);
    });
}

    {% endif %}
  </script>
</html>

EditableFlask/templates/login_prompt.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Login Page</title>
  <link rel="icon" type="image/x-icon" href="/static/favicon.ico">
  <!-- Include Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <style>
    /* Custom styles for this template */
    body {
      display: flex;
      flex-direction: column;
      min-height: 100vh;
    }
    main {
      flex: 1 0 auto;
    }
    .navbar-brand {
      font-size: 36px; /* Increase font size */
      margin-top: auto; /* Center vertically */
      margin-bottom: auto; /* Center vertically */
    }
    .submit-btn {
      text-align: right; /* Align submit button to the right */
    }
    .footer {
      position: absolute;
      bottom:25px;
      left: 0;
      width: 100%;
      text-align: center;
    }
  </style>
</head>
<body>

  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="#">Login</a>
      </div>
    </nav>
  </header>

  <main role="main" class="flex-shrink-0">
    <div class="container">
      <form method="POST">
        <div class="form-group">
          <label for="exampleInputEmail1">Username</label>
          <input type="text" class="form-control" id="exampleInputEmail1" name="username" aria-describedby="emailHelp" placeholder="Enter username`">
          <small id="emailHelp" class="form-text text-muted">If you've only setup password, your username will be same as your password.</small>
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">Password</label>
          <input type="password" class="form-control" id="exampleInputPassword1" name="password" placeholder="Password">
        </div>
        <div class="submit-btn">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </form>
    </div>
  </main>

  <!-- Footer -->
  <footer class="footer">
    <div class="container">
      <span class="text-muted">Powered by Editable Flask created by Mahir Shah</span>
    </div>
  </footer>

  <!-- Include Bootstrap JS -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>